-- 10.1
INSERT INTO OTROS_PROFESIONALES (
   SELECT
      *
   FROM
      PROFESIONAL
   WHERE
      COD_PROFESION = 5
      OR COD_PROFESION = 6 MINUS (
         SELECT
            *
         FROM
            OTROS_PROFESIONALES
         WHERE
            COD_PROFESION = 5
            OR COD_PROFESION = 6));

-- 10.2
INSERT INTO CONTADOR_AUDITOR (
   SELECT
      *
   FROM
      PROFESIONAL
   WHERE
      COD_PROFESION = 1
      AND COD_TPCONTRATO = 1
      AND NUMRUN_PROF IN (
         SELECT
            NUMRUN_PROF
         FROM
            ASESORIA
         HAVING
            COUNT(NUMRUN_PROF) > 5
         GROUP BY
            NUMRUN_PROF));

-- 10.3
INSERT INTO HABERES_MES (
   SELECT
      NUMRUN_PROF, DVRUN_PROF, EXTRACT(YEAR FROM SYSDATE) || EXTRACT(MONTH FROM SYSDATE), SUELDO, ROUND(0.4 * SUM(HONORARIO)), SUELDO * ASIGNACION / 100, SUELDO * PORC_HONORARIO, SUELDO + (ROUND(0.4 * SUM(HONORARIO))) + (SUELDO * PORC_HONORARIO) + (SUELDO * ASIGNACION / 100)
   FROM
      PROFESION
      JOIN PROFESIONAL USING (COD_PROFESION)
      JOIN ASESORIA USING (NUMRUN_PROF)
      JOIN RANGOS_SUELDOS ON (SUELDO BETWEEN SUELDO_MIN
         AND SUELDO_MAX)
   WHERE
      EXTRACT(MONTH FROM FIN_ASESORIA) = 09
      AND EXTRACT(YEAR FROM FIN_ASESORIA) = 2018
   GROUP BY
      NUMRUN_PROF, DVRUN_PROF, SUELDO, ASIGNACION, PORC_HONORARIO
   ORDER BY
      1);
