-- 2.1
SELECT
   TO_CHAR(RUT, '99G999G999') || '-' || DV AS RUN,
   APELLIDOS || ' ' || NOMBRES AS EMPLEADO,
   EMAIL,
   ZONA,
   TO_CHAR(SUELDO, '$999G999G999') AS SUELDO
FROM
   EMPLEADO
WHERE
   SUELDO > 1500000
ORDER BY
   4;

-- 2.2
SELECT
   TO_CHAR(RUT, '99G999G999') || '-' || DV AS RUN,
   APELLIDOS || ' ' || NOMBRES AS EMPLEADO,
   EMAIL,
   FECNAC AS NACIMIENTO,
   TO_CHAR(SUELDO, '$999G999G999') AS SUELDO
FROM
   EMPLEADO
WHERE
   EXTRACT(MONTH FROM SYSDATE) = EXTRACT(MONTH FROM FECNAC);

-- 2.3
SELECT
   TO_CHAR(RUT, '99G999G999') || '-' || DV AS RUN,
   APELLIDOS || ' ' || NOMBRES AS EMPLEADO,
   ZONA,
   RUTEMPRESA,
   TO_CHAR(SUELDO, '$999G999G999') AS SUELDO,
   TO_CHAR((SUELDO * 1.2),
      '$999G999G999') AS "SUELDO AUMENTADO",
   TO_CHAR((SUELDO * 0.2),
      '$999G999G999') AS "DIFERENCIA"
FROM
   EMPLEADO
WHERE
   UPPER(ZONA)
   NOT LIKE 'CE%';

-- 2.4
SELECT
   TO_CHAR(RUT, '99G999G999') || '-' || DV AS RUN,
   APELLIDOS || ' ' || NOMBRES AS EMPLEADO,
   ZONA,
   NUMPROYECTOS,
   TO_CHAR(SUELDO, '$999G999G999') AS SUELDO
FROM
   EMPLEADO
WHERE
   NUMPROYECTOS BETWEEN 8
   AND 13
ORDER BY
   4 DESC,
   APELLIDOS ASC;

-- 2.5
SELECT
   *
FROM
   EMPLEADO
WHERE
   SUBSTR(APELLIDOS, 3, 2) = 'ch';

-- 2.6
SELECT
   *
FROM
   EMPLEADO
WHERE (UPPER(ZONA) <> 'CENTRO'
   AND UPPER(ZONA) <> 'NORTE'
   AND UPPER(ZONA) <> 'PONIENTE')
OR RUTEMPRESA IS NULL;
