-- 3.1
SELECT
   SUBSTR(RUTEMP, 1, (LENGTH(RUTEMP) - 1)) || '-' || SUBSTR(RUTEMP, - 1) AS RUT,
   PATERNO || ' ' || MATERNO || ' ' || NOMBRE AS NOMBRE,
   DIRECCION,
   FONO1,
   NVL (FONO2,
      'NO POSEE FONO')
FROM
   EMPLEADO
ORDER BY
   PATERNO;

-- 3.2
SELECT
   SUBSTR(RUTEMP, 1, (LENGTH(RUTEMP) - 1)) || '-' || SUBSTR(RUTEMP, - 1) AS RUT,
   TRIM(TO_CHAR(SUELDO, '$999G999G999')) AS SUELDO,
   ROUND(SUELDO * 0.00001) || '%' AS PORCENTAJE
FROM
   EMPLEADO
WHERE
   IDCATEGORIA = 2;

-- 3.3
SELECT
   PATERNO || ' ' || MATERNO || ' ' || NOMBRE AS EMPLEADO,
   SUBSTR(NOMBRE, 0, 2) || '.' || PATERNO AS NOM_USUARIO,
   LOWER(SUBSTR(ECIVIL, 1, 1)) || '*' || SUBSTR(RUTEMP, 1, 4) || LOWER(SUBSTR(DIRECCION, 0, 1)) || '_' || SUBSTR(DIRECCION, 2, 1) AS CONTRASE A
FROM
   EMPLEADO
ORDER BY
   NOMBRE;

-- 3.4
SELECT
   SUBSTR(RUTEMP, 1, (LENGTH(RUTEMP) - 1)) || '-' || SUBSTR(RUTEMP, - 1) AS RUT,
   PATERNO || ' ' || MATERNO || ' ' || NOMBRE AS NOMBRE,
   TRIM(TO_CHAR(SUELDO, '$999G999G999')) AS SUELDO,
   CASE WHEN PUNTAJE > 500 THEN
      SUELDO * 1.35
      WHEN PUNTAJE BETWEEN 401
      AND 500 THEN
      SUELDO * 1.25
      WHEN PUNTAJE BETWEEN 301
      AND 400 THEN
      SUELDO * 1.15
      WHEN PUNTAJE BETWEEN 100
      AND 300 THEN
      SUELDO * 1.10
   ELSE
      SUELDO
   END AS "SUELDO AUMENTADO"
FROM
   EMPLEADO
ORDER BY
   PATERNO;

-- 3.5
SELECT
   NUMPROPIEDAD,
   IDTIPO AS TIPO,
   TRIM(TO_CHAR(RENTA, '$999G999G999')) AS RENTA,
   TRIM(TO_CHAR((NVL (GASTOCOMUN, 0)),
         '$999G999G999')) AS "GASTOS COMUNES",
   TRIM(TO_CHAR(RENTA * 1.062, '$999G999G999')) AS "RENTA AJUSTADA",
   TRIM(TO_CHAR((NVL (GASTOCOMUN, 0) * 1.062),
         '$999G999G999')) AS "GASTOS COMUNES AJUSTADOS"
FROM
   PROPIEDAD;

-- 3.6
SELECT
   RUTCLI,
   NOMCLI,
   DIRECCION,
   FONO1,
   FONO2,
   RENTAMAXIMA,
   IDCOMUNA,
   IDTIPO
FROM
   CLIENTE
WHERE
   ECIVIL = 'Soltero'
ORDER BY
   NOMCLI DESC;
