-- 4.1

SELECT SUBSTR(RUTPROF, 1, (LENGTH(RUTPROF) - 1)) || '-' || SUBSTR(RUTPROF, - 1) AS RUT,
      IDEMPRESA AS EMPRESA,
      TO_CHAR(HONORARIO,'$999G999G999') AS HONORARIO,
      INICIO AS INICIO_ASESORIA,
      FIN AS "TERMINO_ASESORIA"
FROM ASESORIA WHERE FIN='30-07-2017'
ORDER BY 2;

--4.2

SELECT SUBSTR(RUTPROF, 1, (LENGTH(RUTPROF) - 1)) || '-' || SUBSTR(RUTPROF, - 1) AS "RUT PROFESIONAL",
      IDEMPRESA AS EMPRESA,
      TO_CHAR(HONORARIO,'$999G999G999') AS HONORARIO,
      INICIO AS INICIO_ASESORIA,
      FIN AS "TERMINO_ASESORIA"
FROM ASESORIA WHERE FIN='01-08-2017';

-- 4.3

SELECT SUBSTR(RUTPROF, 1, (LENGTH(RUTPROF) - 1)) || '-' || SUBSTR(RUTPROF, - 1) AS "RUT PROFESIONAL",
      IDEMPRESA AS EMPRESA,
      TO_CHAR(HONORARIO,'$999G999G999') AS HONORARIO,
      INICIO AS INICIO_ASESORIA,
      FIN AS "TERMINO_ASESORIA"
FROM ASESORIA where fin between '30-07-2017' and '06-08-2017';
