-- 5.1
SELECT
    TO_CHAR(Max(salario), '$999G999G999') AS "SALARIO MÁXIMO",
    TO_CHAR(Min(salario), '$999G999G999') AS "SALARIO MÍNIMO",
    TO_CHAR(Sum(salario), '$999G999G999') AS "SUMATORIA DE LOS SALARIOS",
    TO_CHAR(Avg(salario), '$999G999G999') AS "SALARIO PROMEDIO"
FROM
    EMPLEADO;

-- 5.2
SELECT
    TITULOID AS "CÓDIGO DEL LIBRO",
    Count(*) AS "TOTAL DE EJEMPLARES"
FROM
    EJEMPLAR
GROUP BY
    TITULOID
ORDER BY
    2 ASC,
    1;

-- 5.3
SELECT
    CARRERAID AS "CÓDIGO DE LA CARRERA",
    Count(*) AS "TOTAL DE ALUMNOS"
FROM
    ALUMNO
GROUP BY
    CARRERAID
HAVING
    Count(CARRERAID) > 4
ORDER BY
    2 DESC,
    1 ASC;

-- 5.4
SELECT
    TO_CHAR(RUN_JEFE, '99G999G999') AS "RUN JEFE",
    Count(*) AS "TOTAL DE EMPLEADOS A SU CARGO",
    Max(SALARIO) AS "SALARIO MAXIMO",
    Max(SALARIO) * Count(*) / 100 AS "BONIFICACIÓN"
FROM
    EMPLEADO
WHERE
    RUN_JEFE IS NOT NULL
GROUP BY
    RUN_JEFE
ORDER BY
    1 ASC;

-- 5.5
SELECT
    EM.ID_ESCOLARIDAD AS "ESCOLARIDAD",
    ES.DESC_ESCOLARIDAD AS "DESCRIPCIÓN ESCOLARIDAD",
    Count(*) AS "TOTAL DE EMPLEADOS",
    TO_CHAR(Max(SALARIO), '$999G999G999') AS "SALARIO MÁXIMO",
    TO_CHAR(Min(SALARIO), '$999G999G999') AS "SALARIO MINIMO",
    TO_CHAR(Sum(SALARIO), '$999G999G999') AS "SALARIO TOTAL",
    TO_CHAR(Avg(SALARIO), '$999G999G999') AS "SALARIO PROMEDIO"
FROM
    EMPLEADO EM,
    ESCOLARIDAD_EMP ES
WHERE
    EM.ID_ESCOLARIDAD = ES.ID_ESCOLARIDAD
GROUP BY
    EM.ID_ESCOLARIDAD,
    ES.DESC_ESCOLARIDAD
ORDER BY
    3 DESC;

-- 5.6
SELECT
    TITULOID,
    Count(*),
    'SE REQUIERE COMPRAR ' || Count(*) || ' NUEVOS EJEMPLARES' AS "OBS PRESUPUESTARIA"
FROM
    PRESTAMO
WHERE
    FECHA_INI_PRESTAMO > TRUNC(SYSDATE - 365 * 1, 'YEAR')
GROUP BY
    TITULOID
ORDER BY
    1 ASC;

-- 5.7
SELECT
    RUN_EMP,
    TO_CHAR(P.FECHA_INI_PRESTAMO, 'MM/YYYY'),
    COUNT(*)
FROM
    PRESTAMO P
WHERE
    TO_CHAR(P.FECHA_INI_PRESTAMO, 'YYYY') = 2019
GROUP BY
    RUN_EMP,
    TO_CHAR(P.FECHA_INI_PRESTAMO, 'MM/YYYY')
ORDER BY
    2,
    1;

SELECT
    *
FROM
    PRESTAMO;
