
-- 6.1
SELECT
    A.CARRERAID AS "CÓDIGO CARRERA",
    C.DESCRIPCION AS "NOMBRE CARRERA",
    A.NOMBRE || ' ' || A.APATERNO || ' ' || A.AMATERNO AS "NOMBRE ALUMNO"
FROM
    CARRERA C,
    ALUMNO A
WHERE
    C.CARRERAID = A.CARRERAID
ORDER BY
    2,
    A.APATERNO;

SELECT
    C.CARRERAID AS "CÓDIGO DE CARRERA",
    C.DESCRIPCION AS "NOMBRE DE CARRERA",
    A.NOMBRE || ' ' || A.APATERNO || ' ' || A.AMATERNO AS "NOMBRE ALUMNO"
FROM
    ALUMNO A
    JOIN CARRERA C ON A.CARRERAID = C.CARRERAID
ORDER BY
    2,
    A.APATERNO;

-- 6.2
SELECT
    Upper(E.DESCRIPCION),
    Count(*)
FROM
    ESCUELA E
    JOIN CARRERA C ON C.ESCUELAID = E.ESCUELAID
GROUP BY
    E.DESCRIPCION
ORDER BY
    2 DESC,
    1 ASC;

-- 6.3
SELECT
    C.DESCRIPCION,
    Count(*)
FROM
    CARRERA C
    JOIN ALUMNO A ON C.CARRERAID = A.CARRERAID
GROUP BY
    C.DESCRIPCION
ORDER BY
    2 DESC;

-- 6.4
SELECT
    A.NOMBRE || ' ' || A.APATERNO || ' ' || A.AMATERNO AS "NOMBRE ALUMNO",
    P.FECHA_INI_PRESTAMO AS "FECHA INICIO PRESTAMO",
    P.FECHA_TER_PRESTAMO AS "FECHA TERMINO PRESTAMO",
    P.FECHA_DEVOLUCION AS "FECHA DEVOLUCION",
    P.FECHA_DEVOLUCION - P.FECHA_TER_PRESTAMO AS "DIAS DE ATRASO",
    TO_CHAR(((P.FECHA_DEVOLUCION - P.FECHA_TER_PRESTAMO) * 1000),
        '$999G999G999') AS "VALOR MULTA"
FROM
    ALUMNO A
    JOIN PRESTAMO P ON A.ALUMNOID = P.ALUMNOID
WHERE
    TO_CHAR(P.FECHA_DEVOLUCION, 'MM') = 07
    AND TO_CHAR(P.FECHA_DEVOLUCION, 'YYYY') = 2018
    AND (P.FECHA_DEVOLUCION - P.FECHA_TER_PRESTAMO) > 0
ORDER BY
    A.APATERNO,
    6 DESC;

-- 6.5