-- 7.1
SELECT
    TO_CHAR(A.JEFE_RUT, '99G999G999') AS "RUT JEFE",
    B.PNOMBRE || ' ' || B.SNOMBRE || ' ' || B.APATERNO || ' ' || B.AMATERNO AS "NOMBRE JEFE",
    TO_CHAR(B.SUELDO_BASE, '$999G999G999') AS "SUELDO BASE",
    COUNT(*) AS "TOTAL MÉDICOS A SU CARGO",
    TO_CHAR(ROUND(B.SUELDO_BASE * COUNT(*) * 0.01), '$999G999G999') AS "ASIGNACIÓN JEFE"
FROM
    MEDICO A
    JOIN MEDICO B ON A.JEFE_RUT = B.MED_RUT
GROUP BY
    A.JEFE_RUT,
    B.PNOMBRE,
    B.SNOMBRE,
    B.APATERNO,
    B.AMATERNO,
    B.SUELDO_BASE
ORDER BY
    B.APATERNO;

-- 7.2
SELECT
    TO_CHAR(MED_RUT, '999G999G999') || '-' || DV_RUT AS "RUT MÉDICO",
    PNOMBRE || ' ' || SNOMBRE || ' ' || APATERNO || ' ' || AMATERNO AS "MÉDICO",
    EXTRACT(MONTH FROM FECHA_ATENCION) AS "MES ATENCIONES MÉDICAS",
    TO_CHAR(SUELDO_BASE * COUNT(*) * 0.01, '$999G999G999') AS "BONIF. POR ATENCIONES MÉDICAS"
FROM
    ATENCION
    NATURAL JOIN MEDICO
WHERE
    EXTRACT(MONTH FROM FECHA_ATENCION) = EXTRACT(MONTH FROM SYSDATE) - 1
    AND EXTRACT(YEAR FROM FECHA_ATENCION) = EXTRACT(YEAR FROM SYSDATE)
GROUP BY
    MED_RUT,
    PNOMBRE,
    SNOMBRE,
    APATERNO,
    AMATERNO,
    MED_RUT,
    DV_RUT,
    EXTRACT(MONTH FROM FECHA_ATENCION),
    SUELDO_BASE
HAVING
    COUNT(*) > 1
ORDER BY
    4 DESC,
    APATERNO ASC;

-- 7.3
SELECT
    U.NOMBRE,
    C.NOMBRE,
    NVL (COUNT(ESP_ID),
        0)
FROM
    CARGO C
    JOIN MEDICO M ON C.CAR_ID = M.CAR_ID
    JOIN UNIDAD U ON M.UNI_ID = U.UNI_ID
    RIGHT JOIN ATENCION A ON A.MED_RUT = M.MED_RUT
GROUP BY
    C.NOMBRE,
    U.NOMBRE
ORDER BY
    1 ASC,
    COUNT(C.NOMBRE)
    DESC;

-- 7.4
SELECT
    ATE_ID,
    FECHA_ATENCION,
    PAC_RUT,
    P.PNOMBRE || ' ' || SNOMBRE || ' ' || APATERNO || ' ' || AMATERNO,
    S.TIPO_SAL_ID || ', ' || S.DESCRIPCION
FROM
    ATENCION
    NATURAL JOIN PACIENTE P
    NATURAL JOIN SALUD S
WHERE
    EXTRACT(MONTH FROM FECHA_ATENCION) = 7
    AND EXTRACT(YEAR FROM FECHA_ATENCION) = EXTRACT(YEAR FROM SYSDATE) - 1
ORDER BY
    FECHA_ATENCION ASC;

-- 7.5
SELECT
    PNOMBRE || ' ' || SNOMBRE || ' ' || APATERNO || ' ' || AMATERNO AS "MÉDICO",
    NOMBRE AS "UNIDAD",
    SUBSTR(U.NOMBRE, 0, 2) || SUBSTR(APATERNO, LENGTH(APATERNO) - 2, 2) || SUBSTR(TELEFONO, 0, 3) || EXTRACT(YEAR FROM FECHA_CONTRATO) || '@MEDICOCKTK.CL' AS "CORREO MÉDICO",
    COUNT(MED_RUT) AS "ATENCIONES MÉDICAS"
FROM
    MEDICO M
    NATURAL JOIN UNIDAD U
    NATURAL JOIN ATENCION A
GROUP BY
    PNOMBRE,
    SNOMBRE,
    APATERNO,
    AMATERNO,
    NOMBRE,
    TELEFONO,
    FECHA_CONTRATO
ORDER BY
    COUNT(MED_RUT) ASC,
    APATERNO ASC;

-- 7.6
SELECT
    PNOMBRE || ' ' || SNOMBRE || ' ' || APATERNO || ' ' || AMATERNO AS "NOMBRE DEL PACIENTE",
    COUNT(PAC_RUT)
FROM
    PACIENTE
    NATURAL JOIN ATENCION
GROUP BY
    PAC_RUT,
    PNOMBRE,
    SNOMBRE,
    APATERNO,
    AMATERNO
ORDER BY
    APATERNO,
    PNOMBRE;

-- 7.7
SELECT
    TO_CHAR(PAC_RUT, '99G999G999') || '-' || DV_RUT AS "RUT PACIENTE",
    PNOMBRE || ' ' || SNOMBRE || ' ' || APATERNO || ' ' || AMATERNO AS "NOMBRE PACIENTE",
    TRUNC((SYSDATE - FECHA_NACIMIENTO) / 365) AS "AÑOS",
    FECHA_ATENCION || ' ' || HR_ATENCION AS "FECHA Y HORA DE ATENCIÓN",
    TO_CHAR(COSTO, '$999G999G999') AS "COSTO ATENCION S/DESCUENTO",
    TO_CHAR(COSTO - ROUND(PORCENTAJE_DESCTO * 0.01 * COSTO), '$999G999G999') AS "COSTO ATENCIÓN C/DESCUENTO",
    TO_CHAR(ROUND(PORCENTAJE_DESCTO * 0.01 * COSTO), '$999G999G999') AS "MONTO A DEVOLVER"
FROM
    ATENCION
    NATURAL JOIN PACIENTE
    JOIN PORC_DESCTO_3RA_EDAD P ON (TRUNC((SYSDATE - FECHA_NACIMIENTO) / 365))
    BETWEEN ANNO_INI
    AND ANNO_TER
WHERE
    TRUNC((SYSDATE - FECHA_NACIMIENTO) / 365) > 65
ORDER BY
    FECHA_ATENCION ASC,
    TRUNC((SYSDATE - FECHA_NACIMIENTO) / 365)
    DESC;