-- 8.1
SELECT
    NOMBRE,
    PNOMBRE || ' ' || SNOMBRE || ' ' || APATERNO || ' ' || AMATERNO AS "MEDICO",
    SUBSTR(U.NOMBRE, 0, 2) || SUBSTR(APATERNO, LENGTH(APATERNO) - 2, 2) || SUBSTR(TELEFONO, 0, 3) || EXTRACT(YEAR FROM FECHA_CONTRATO) || '@MEDICOCKTK.CL' AS "CORREO MÉDICO",
    COUNT(MED_RUT)
FROM
    ATENCION
    NATURAL JOIN MEDICO
    NATURAL JOIN UNIDAD U
WHERE
    EXTRACT(YEAR FROM FECHA_ATENCION) = 2017
GROUP BY
    PNOMBRE,
    SNOMBRE,
    APATERNO,
    AMATERNO,
    TELEFONO,
    FECHA_CONTRATO,
    MED_RUT,
    NOMBRE
HAVING
    COUNT(MED_RUT) < (
      SELECT
         MAX(TOTAL)
      FROM (
         SELECT
            COUNT(*) AS TOTAL
         FROM
            ATENCION
         WHERE
            EXTRACT(YEAR FROM FECHA_ATENCION) = (EXTRACT(YEAR FROM SYSDATE) - 1)
         GROUP BY
            MED_RUT))
    ORDER BY
        1,
        APATERNO,
        AMATERNO;
SELECT
   MAX(TOTAL)
FROM (
   SELECT
      COUNT(*) AS TOTAL
   FROM
      ATENCION
   WHERE
      EXTRACT(YEAR FROM FECHA_ATENCION) = (EXTRACT(YEAR FROM SYSDATE) - 1)
   GROUP BY
      MED_RUT)

         ;
-- 8.2.1
SELECT
    EXTRACT(MONTH FROM FECHA_ATENCION) || '/2017' AS "MES Y AÑO",
    COUNT(*) AS "TOTAL DE ATENCIONES",
    TO_CHAR(SUM(COSTO), '$999G999G999') AS "VALOR TOTAL DE LAS ATENCIONES"
FROM
    ATENCION
WHERE
    EXTRACT(YEAR FROM FECHA_ATENCION) = 2017
GROUP BY
    EXTRACT(MONTH FROM FECHA_ATENCION)
HAVING
    COUNT(*) > (
        SELECT
            AVG(COUNT(*))
        FROM
            ATENCION
        WHERE
            EXTRACT(YEAR FROM FECHA_ATENCION) = 2017
        GROUP BY
            EXTRACT(MONTH FROM FECHA_ATENCION))
    ORDER BY
        EXTRACT(MONTH FROM FECHA_ATENCION) ASC;

-- 8.2.2

SELECT
    PAC_RUT || '-' || DV_RUT AS "RUT PACIENTE",
    PNOMBRE || ' ' || SNOMBRE || ' ' || APATERNO || ' ' || AMATERNO AS "NOMBRE PACIENTE",
    ATE_ID AS "ID ATENCION",
    FECHA_VENC_PAGO AS "FECHA VENCIMIENTO PAGO",
    FECHA_PAGO AS "FECHA PAGO", (FECHA_PAGO - FECHA_VENC_PAGO) AS "DIAS MOROSIDAD",
    TO_CHAR(((FECHA_PAGO - FECHA_VENC_PAGO) * 2000),
        '$999G999G999') AS "VALOR MULTA"
FROM
    PACIENTE
    NATURAL JOIN ATENCION
    NATURAL JOIN PAGO_ATENCION
WHERE (FECHA_PAGO - FECHA_VENC_PAGO) > (
    SELECT
        AVG(FECHA_PAGO - FECHA_VENC_PAGO)
    FROM
        PAGO_ATENCION);


-- 8.3

SELECT
    T.DESCRIPCION || ', ' || S.DESCRIPCION AS "SISTEMA SALUD",
    COUNT(S.DESCRIPCION) AS "TOTAL ATENCIONES"
FROM
    ATENCION A
    JOIN PACIENTE P USING (PAC_RUT)
    JOIN SALUD S USING (SAL_ID)
    JOIN TIPO_SALUD T USING (TIPO_SAL_ID)
WHERE
    FECHA_ATENCION BETWEEN LAST_DAY (ADD_MONTHS (SYSDATE, - 2)) + 1
    AND LAST_DAY (ADD_MONTHS (SYSDATE, - 1))
GROUP BY
    S.DESCRIPCION,
    T.DESCRIPCION
HAVING
    COUNT(S.DESCRIPCION) > (
        SELECT
            AVG(COUNT(S.DESCRIPCION))
        FROM
            ATENCION A
            JOIN PACIENTE P USING (PAC_RUT)
            JOIN SALUD S USING (SAL_ID)
        WHERE
            FECHA_ATENCION BETWEEN LAST_DAY (ADD_MONTHS (SYSDATE, - 2)) + 1
            AND LAST_DAY (ADD_MONTHS (SYSDATE, - 1))
        GROUP BY
            S.DESCRIPCION);

-- 8.4

SELECT
    PNOMBRE || ' ' || SNOMBRE || ' ' || APATERNO || ' ' || AMATERNO AS MEDICO,
    MED_RUT || '-' || DV_RUT AS RUT,
    NOMBRE
FROM
    MEDICO
    JOIN ESPECIALIDAD_MEDICO USING (MED_RUT)
    JOIN ESPECIALIDAD USING (ESP_ID)
WHERE
    ESP_ID IN (
        SELECT
            ESP_ID
        FROM
            ATENCION FULL OUTER JOIN ESPECIALIDAD USING (ESP_ID)
        WHERE
            EXTRACT(YEAR FROM FECHA_ATENCION) = (EXTRACT(YEAR FROM SYSDATE) - 1)
        GROUP BY
            ESP_ID
        HAVING
            COUNT(ESP_ID) < 10)

    ORDER BY
        NOMBRE ASC,
        APATERNO ASC;
