-- 9.1

SELECT
   TO_CHAR(NUMRUN_PROF, '999G999G999') || '-' || DVRUN_PROF AS "RUN PROFESIONAL",
   NOMBRE || ' ' || APPATERNO || ' ' || APMATERNO AS "NOMBRE PROFESIONAL",
   NOMBRE_PROFESION AS "PROFESIÓN"
FROM
   PROFESIONAL
   JOIN PROFESION USING (COD_PROFESION)
WHERE
   COD_PROFESION = 5
   OR COD_PROFESION = 6 MINUS (
      SELECT
         TO_CHAR(NUMRUN_PROF, '999G999G999') || '-' || DVRUN_PROF AS "RUN PROFESIONAL", NOMBRE || ' ' || APPATERNO || ' ' || APMATERNO AS "NOMBRE PROFESIONAL", NOMBRE_PROFESION AS "PROFESIÓN"
      FROM
         OTROS_PROFESIONALES
         JOIN PROFESION USING (COD_PROFESION)
      WHERE
         COD_PROFESION = 5
         OR COD_PROFESION = 6
      UNION ALL
      SELECT
         TO_CHAR(NUMRUN_PROF, '999G999G999') || '-' || DVRUN_PROF AS "RUN PROFESIONAL",
         NOMBRE || ' ' || APPATERNO || ' ' || APMATERNO AS "NOMBRE PROFESIONAL",
         NOMBRE_PROFESION AS "PROFESIÓN"
      FROM
         PREVENCIONISTA
         JOIN PROFESION USING (COD_PROFESION))
   ORDER BY
      1;

-- 9.2

SELECT
   TO_CHAR(NUMRUN_PROF, '999G999G999') || '-' || DVRUN_PROF AS "RUN PROFESIONAL",
   NOMBRE || ' ' || APPATERNO || ' ' || APMATERNO AS "NOMBRE PROFESIONAL",
   NOMBRE_PROFESION AS "PROFESIÓN"
FROM
   CONTADOR_AUDITOR
   JOIN PROFESION USING (COD_PROFESION)
INTERSECT
SELECT
   TO_CHAR(NUMRUN_PROF, '999G999G999') || '-' || DVRUN_PROF AS "RUN PROFESIONAL",
   NOMBRE || ' ' || APPATERNO || ' ' || APMATERNO AS "NOMBRE PROFESIONAL",
   NOMBRE_PROFESION AS "PROFESIÓN"
FROM
   CONTADOR_GENERAL
   JOIN PROFESION USING (COD_PROFESION)
ORDER BY
   1;

-- 9.3

SELECT
   TO_CHAR(NUMRUN_PROF, '999G999G999') || '-' || DVRUN_PROF AS "RUN PROFESIONAL",
   NOMBRE || ' ' || APPATERNO || ' ' || APMATERNO AS "NOMBRE PROFESIONAL",
   NOMBRE_PROFESION AS "PROFESIÓN"
FROM
   OTROS_PROFESIONALES
   JOIN PROFESION USING (COD_PROFESION)
INTERSECT
SELECT
   TO_CHAR(NUMRUN_PROF, '999G999G999') || '-' || DVRUN_PROF AS "RUN PROFESIONAL",
   NOMBRE || ' ' || APPATERNO || ' ' || APMATERNO AS "NOMBRE PROFESIONAL",
   NOMBRE_PROFESION AS "PROFESIÓN"
FROM
   PROFESIONAL
   JOIN PROFESION USING (COD_PROFESION)
WHERE
   COD_PROFESION = 4;

-- 9.4

SELECT
   'TABLA ANTIGUA' AS "ORIGEN DE LOS DATOS",
   NOMBRE_PROFESION,
   COUNT(*) AS "TOTAL EMPLEADOS"
FROM
   PROFESIONAL
   JOIN PROFESION USING (COD_PROFESION)
WHERE
   COD_PROFESION = 2
GROUP BY
   COD_PROFESION,
   NOMBRE_PROFESION
UNION
SELECT
   'NUEVA TABLA',
   NOMBRE_PROFESION,
   COUNT(*) AS "TOTAL EMPLEADOS"
FROM
   CONTADOR_GENERAL
   JOIN PROFESION USING (COD_PROFESION)
WHERE
   COD_PROFESION = 2
GROUP BY
   NOMBRE_PROFESION;

--------------------------

SELECT
   'TABLA ANTIGUA' AS "ORIGEN DE LOS DATOS",
   NOMBRE_PROFESION,
   COUNT(*) AS "TOTAL EMPLEADOS"
FROM
   PROFESIONAL
   JOIN PROFESION USING (COD_PROFESION)
WHERE
   COD_PROFESION = 1
GROUP BY
   COD_PROFESION,
   NOMBRE_PROFESION
UNION
SELECT
   'NUEVA TABLA',
   NOMBRE_PROFESION,
   COUNT(*) AS "TOTAL EMPLEADOS"
FROM
   CONTADOR_AUDITOR
   JOIN PROFESION USING (COD_PROFESION)
WHERE
   COD_PROFESION = 1
GROUP BY
   NOMBRE_PROFESION;

--------------------------

SELECT
   *
FROM
   PROFESION;

SELECT
   'TABLA ANTIGUA' AS "ORIGEN DE LOS DATOS",
   NOMBRE_PROFESION,
   COUNT(*) AS "TOTAL EMPLEADOS"
FROM
   PROFESIONAL
   JOIN PROFESION USING (COD_PROFESION)
WHERE
   COD_PROFESION = 3
GROUP BY
   COD_PROFESION,
   NOMBRE_PROFESION
UNION
SELECT
   'NUEVA TABLA',
   NOMBRE_PROFESION,
   COUNT(*) AS "TOTAL EMPLEADOS"
FROM
   INFORMATICO
   JOIN PROFESION USING (COD_PROFESION)
WHERE
   COD_PROFESION = 3
GROUP BY
   NOMBRE_PROFESION;

--------------------------

SELECT
   'TABLA ANTIGUA' AS "ORIGEN DE LOS DATOS",
   NOMBRE_PROFESION,
   COUNT(*) AS "TOTAL EMPLEADOS"
FROM
   PROFESIONAL
   JOIN PROFESION USING (COD_PROFESION)
WHERE
   COD_PROFESION = 4
GROUP BY
   COD_PROFESION,
   NOMBRE_PROFESION
UNION
SELECT
   'NUEVA TABLA',
   NOMBRE_PROFESION,
   COUNT(*) AS "TOTAL EMPLEADOS"
FROM
   PREVENCIONISTA
   JOIN PROFESION USING (COD_PROFESION)
WHERE
   COD_PROFESION = 4
GROUP BY
   NOMBRE_PROFESION;

--------------------------

SELECT
   'NUEVA TABLA',
   NOMBRE_PROFESION,
   COUNT(NUMRUN_PROF) AS "TOTAL EMPLEADOS"
FROM
   OTROS_PROFESIONALES
   RIGHT JOIN PROFESION USING (COD_PROFESION)
WHERE
   COD_PROFESION = 5
GROUP BY
   NOMBRE_PROFESION
UNION ALL
SELECT
   'TABLA ANTIGUA' AS "ORIGEN DE LOS DATOS",
   NOMBRE_PROFESION,
   COUNT(*) AS "TOTAL EMPLEADOS"
FROM
   PROFESIONAL
   JOIN PROFESION USING (COD_PROFESION)
WHERE
   COD_PROFESION = 5
GROUP BY
   NOMBRE_PROFESION;

--------------------------

SELECT
   'NUEVA TABLA',
   NOMBRE_PROFESION,
   COUNT(NUMRUN_PROF) AS "TOTAL EMPLEADOS"
FROM
   OTROS_PROFESIONALES
   RIGHT JOIN PROFESION USING (COD_PROFESION)
WHERE
   COD_PROFESION = 6
GROUP BY
   NOMBRE_PROFESION
UNION ALL
SELECT
   'TABLA ANTIGUA' AS "ORIGEN DE LOS DATOS",
   NOMBRE_PROFESION,
   COUNT(NUMRUN_PROF) AS "TOTAL EMPLEADOS"
FROM
   PROFESIONAL
   JOIN PROFESION USING (COD_PROFESION)
WHERE
   COD_PROFESION = 6
GROUP BY
   NOMBRE_PROFESION;

-- 9.5

SELECT
   TO_CHAR(NUMRUN_PROF, '999G999G999') || '-' || DVRUN_PROF AS "RUN PROFESIONAL",
   NOMBRE,
   APPATERNO AS "APELLIDO PATERNO",
   APMATERNO AS "APELLIDO MATERNO",
   NOMBRE_PROFESION AS "PROFESIÓN"
FROM
   PROFESIONAL
   NATURAL JOIN PROFESION
WHERE
   COD_PROFESION = 1
   OR COD_PROFESION = 2 MINUS (
      SELECT
         TO_CHAR(NUMRUN_PROF, '999G999G999') || '-' || DVRUN_PROF AS "RUN PROFESIONAL", NOMBRE, APPATERNO AS "APELLIDO PATERNO", APMATERNO AS "APELLIDO MATERNO", NOMBRE_PROFESION AS "PROFESIÓN"
      FROM
         CONTADOR_GENERAL
      NATURAL JOIN PROFESION
   UNION
   SELECT
      TO_CHAR(NUMRUN_PROF, '999G999G999') || '-' || DVRUN_PROF AS "RUN PROFESIONAL",
      NOMBRE,
      APPATERNO AS "APELLIDO PATERNO",
      APMATERNO AS "APELLIDO MATERNO",
      NOMBRE_PROFESION AS "PROFESIÓN"
   FROM
      CONTADOR_AUDITOR
   NATURAL JOIN PROFESION)
ORDER BY
   3;
