-- 1
SELECT
   UPPER(EDI_NOMBRE_EDIFICIO) AS "NOMBRE EDIFICIO",
   COUNT(*) AS "TOTAL DEPTOS",
   NVL (C1.CANTIDAD,
      0) AS "TOTAL DEPTOS 1 DORMITORIO",
   NVL (C2.CANTIDAD,
      0) AS "TOTAL DEPTOS 2 DORMITORIOS",
   NVL (C3.CANTIDAD,
      0) AS "TOTAL DEPTOS 3 DORMITORIOS",
   NVL (C4.CANTIDAD,
      0) AS "TOTAL DEPTOS 4 DORMITORIOS",
   NVL (C5.CANTIDAD,
      0) AS "TOTAL DEPTOS 5 DORMITORIOS"
FROM
   EDIFICIO E
   JOIN DEPARTAMENTO D USING (ID_EDIFICIO)
   LEFT JOIN (
      SELECT
         ID_EDIFICIO,
         COUNT(*) AS CANTIDAD
      FROM
         DEPARTAMENTO D
         JOIN EDIFICIO USING (ID_EDIFICIO)
      WHERE
         TOTAL_DORMITORIOS = 1
      GROUP BY
         ID_EDIFICIO) C1 USING (ID_EDIFICIO)
      LEFT JOIN (
         SELECT
            ID_EDIFICIO,
            COUNT(*) AS CANTIDAD
         FROM
            DEPARTAMENTO D
            JOIN EDIFICIO USING (ID_EDIFICIO)
         WHERE
            TOTAL_DORMITORIOS = 2
         GROUP BY
            ID_EDIFICIO) C2 USING (ID_EDIFICIO)
         LEFT JOIN (
            SELECT
               ID_EDIFICIO,
               COUNT(*) AS CANTIDAD
            FROM
               DEPARTAMENTO D
               JOIN EDIFICIO USING (ID_EDIFICIO)
            WHERE
               TOTAL_DORMITORIOS = 3
            GROUP BY
               ID_EDIFICIO) C3 USING (ID_EDIFICIO)
            LEFT JOIN (
               SELECT
                  ID_EDIFICIO,
                  COUNT(*) AS CANTIDAD
               FROM
                  DEPARTAMENTO D
                  JOIN EDIFICIO USING (ID_EDIFICIO)
               WHERE
                  TOTAL_DORMITORIOS = 4
               GROUP BY
                  ID_EDIFICIO) C4 USING (ID_EDIFICIO)
               LEFT JOIN (
                  SELECT
                     ID_EDIFICIO,
                     COUNT(*) AS CANTIDAD
                  FROM
                     DEPARTAMENTO D
                     JOIN EDIFICIO USING (ID_EDIFICIO)
                  WHERE
                     TOTAL_DORMITORIOS = 5
                  GROUP BY
                     ID_EDIFICIO) C5 USING (ID_EDIFICIO)
               GROUP BY
                  EDI_NOMBRE_EDIFICIO, C1.CANTIDAD, C2.CANTIDAD, C3.CANTIDAD, C4.CANTIDAD, C5.CANTIDAD
               ORDER BY
                  1;

-------------------------------------------
-- 2
SELECT
   EDI_NOMBRE_EDIFICIO AS "NOMBRE EDIFICIO",
   NOMBRE_COMUNA AS "COMUNA",
   TO_CHAR(ADM_NUMRUN, '99G999G999') || '-' || ADM_DVRUN AS "RUN ADMINISTRADOR",
   ADM_PNOMBRE || ' ' || ADM_SNOMBRE || ' ' || ADM_APELLIDO_PATERNO || ' ' || ADM_APELLIDO_MATERNO AS "NOMBRE ADMINISTRADOR",
   C1.CANTIDAD AS "TOTAL DEPARTAMENTOS",
   COUNT(*) AS "TOTAL DEPTOS NO CANCELAN GC"
FROM
   GASTO_COMUN
   JOIN EDIFICIO USING (ID_EDIFICIO)
   JOIN COMUNA USING (ID_COMUNA)
   JOIN RESPONSABLE_PAGO_GASTO_COMUN USING (RPGC_NUMRUN)
   JOIN ADMINISTRADOR USING (ADM_NUMRUN)
   JOIN (
      SELECT
         ID_EDIFICIO,
         COUNT(*) AS CANTIDAD
      FROM
         DEPARTAMENTO
      GROUP BY
         ID_EDIFICIO) C1 USING (ID_EDIFICIO)
   WHERE
      PCO_PERIODO = 201907 -- EXTRACT (YEAR FROM (TRUNC((SYSDATE -1), 'MONTH')))||(EXTRACT(MONTH FROM (TRUNC((SYSDATE -1), 'MONTH')))-1)
      AND (NRO_DEPARTAMENTO)
      IN ((
            SELECT
               (NRO_DEPARTAMENTO)
            FROM
               GASTO_COMUN
            WHERE
               PCO_PERIODO = 201907) MINUS ( -- EXTRACT (YEAR FROM (TRUNC((SYSDATE -1), 'MONTH')))||(EXTRACT(MONTH FROM (TRUNC((SYSDATE -1), 'MONTH')))-1)
               SELECT
                  (NRO_DEPARTAMENTO)
               FROM
                  PAGO_GASTO_COMUN
               WHERE
                  PCO_PERIODO = 201907) -- EXTRACT (YEAR FROM (TRUNC((SYSDATE -1), 'MONTH')))||(EXTRACT(MONTH FROM (TRUNC((SYSDATE -1), 'MONTH')))-1)
)
         GROUP BY
            EDI_NOMBRE_EDIFICIO,
            NOMBRE_COMUNA,
            ADM_NUMRUN,
            ADM_DVRUN,
            ADM_PNOMBRE,
            ADM_SNOMBRE,
            ADM_APELLIDO_PATERNO,
            ADM_APELLIDO_MATERNO,
            CANTIDAD
         ORDER BY
            NOMBRE_COMUNA,
            EDI_NOMBRE_EDIFICIO;

-----------------------------------------------------
-- 3
SELECT
   EDI_NOMBRE_EDIFICIO AS "EDIFICIO",
   NRO_DEPARTAMENTO AS "DEPARTAMENTO",
   SUBSTR(PCO_PERIODO, 5, 2) || '/' || SUBSTR(PCO_PERIODO, 1, 4) AS "PERIODO COBRO",
   GAS_FECHA_PAGO AS "FECHA DE PAGO",
   PGC_FECHA_CANCELACION AS "FECHA CANCELACIÓN",
   TO_CHAR(PGC_MONTO_CANCELADO, '$999G999G999') AS "TOTAL GASTO COMÚN",
   PGC_FECHA_CANCELACION - GAS_FECHA_PAGO AS "DÍAS DE MORA",
   CASE WHEN (PGC_FECHA_CANCELACION - GAS_FECHA_PAGO) < 10 THEN
      'SE COBRARÁ COMO MULTA DE PERIODO ' || EXTRACT(MONTH FROM SYSDATE) || '/' || EXTRACT(YEAR FROM SYSDATE) || ' ' || TO_CHAR(0.02 * PGC_MONTO_CANCELADO, '$999G999G999')
      WHEN (PGC_FECHA_CANCELACION - GAS_FECHA_PAGO) < 16 THEN
      'SE COBRARÁ COMO MULTA DE PERIODO ' || EXTRACT(MONTH FROM SYSDATE) || '/' || EXTRACT(YEAR FROM SYSDATE) || ' ' || TO_CHAR(0.04 * PGC_MONTO_CANCELADO, '$999G999G999')
      WHEN (PGC_FECHA_CANCELACION - GAS_FECHA_PAGO) < 21 THEN
      'SE COBRARÁ COMO MULTA DE PERIODO ' || EXTRACT(MONTH FROM SYSDATE) || '/' || EXTRACT(YEAR FROM SYSDATE) || ' ' || TO_CHAR(0.06 * PGC_MONTO_CANCELADO, '$999G999G999')
      WHEN (PGC_FECHA_CANCELACION - GAS_FECHA_PAGO) < 26 THEN
      'SE COBRARÁ COMO MULTA DE PERIODO ' || EXTRACT(MONTH FROM SYSDATE) || '/' || EXTRACT(YEAR FROM SYSDATE) || ' ' || TO_CHAR(0.08 * PGC_MONTO_CANCELADO, '$999G999G999')
   ELSE
      'SE COBRARÁ COMO MULTA DE PERIODO ' || EXTRACT(MONTH FROM SYSDATE) || '/' || EXTRACT(YEAR FROM SYSDATE) || ' ' || TO_CHAR(0.1 * PGC_MONTO_CANCELADO, '$999G999G999')
   END AS "OBSERVACIÓN COBRO MULTAS"
FROM
   PAGO_GASTO_COMUN
   NATURAL JOIN GASTO_COMUN
   JOIN EDIFICIO USING (ID_EDIFICIO)
WHERE
   PGC_FECHA_CANCELACION > GAS_FECHA_PAGO + 5
   AND EXTRACT(MONTH FROM GAS_FECHA_PAGO) = 07 -- EXTRACT (MONTH FROM (TRUNC((SYSDATE -1), 'MONTH')))
   AND EXTRACT(YEAR FROM SYSDATE) = 2019 -- EXTRACT (YEAR FROM (TRUNC((SYSDATE -1), 'MONTH')))
ORDER BY
   7 DESC;

-----------------------------------------------------
-- 4
SELECT
   EDI_NOMBRE_EDIFICIO AS "EDIFICIO",
   NRO_DEPARTAMENTO AS "DEPARTAMENTO",
   TO_CHAR(GAS_GASTO_TOTAL, '$999G999G999') AS "TOTAL GASTO COMÚN",
   TO_CHAR(RPGC_NUMRUN, '99G999G999') || '-' || RPGC_DVRUN AS "RUN RESPONSABLE",
   RPGC_PNOMBRE || ' ' || RPGC_SNOMBRE || ' ' || RPGC_APELLIDO_PATERNO || ' ' || RPGC_APELLIDO_MATERNO AS "NOMBRE RESPONSABLE",
   TP_DESCRIPCION AS "DUEÑO/ARRIENDA/REPRESENTANTE"
FROM
   GASTO_COMUN
   JOIN EDIFICIO USING (ID_EDIFICIO)
   JOIN RESPONSABLE_PAGO_GASTO_COMUN USING (RPGC_NUMRUN)
   JOIN TIPO_PERSONA USING (ID_TIPO_PERSONA)
WHERE
   EXTRACT(MONTH FROM GAS_FECHA_PAGO) = 08 -- EXTRACT(MONTH FROM (TRUNC((SYSDATE -1), 'MONTH')))
   AND EXTRACT(YEAR FROM GAS_FECHA_PAGO) = 2019 -- EXTRACT (YEAR FROM (TRUNC((SYSDATE -1), 'MONTH')))
ORDER BY
   1 ASC,
   2 ASC;

-----------------------------------------------------
-- 5
SELECT
   EDI_NOMBRE_EDIFICIO AS "EDIFICIO",
   GASTO_COMUN.NRO_DEPARTAMENTO AS "DEPARTAMENTO",
   SUBSTR(GASTO_COMUN.PCO_PERIODO, 5, 2) || '/' || SUBSTR(GASTO_COMUN.PCO_PERIODO, 1, 4) AS "PERIODO COBRO",
   TO_CHAR(GAS_GASTO_TOTAL, '$999G999G999') AS "TOTAL GASTO COMÚN",
   TO_CHAR(NVL (PGC_MONTO_CANCELADO, 0),
      '$999G999G999') AS "MONTO CANCELADO",
   TO_CHAR((GAS_GASTO_TOTAL - NVL (PGC_MONTO_CANCELADO, 0)),
      '$999G999G999') AS "DEUDA"
FROM
   EDIFICIO
   JOIN GASTO_COMUN ON (EDIFICIO.ID_EDIFICIO = GASTO_COMUN.ID_EDIFICIO)
   LEFT JOIN PAGO_GASTO_COMUN P ON (P.NRO_DEPARTAMENTO = GASTO_COMUN.NRO_DEPARTAMENTO
      AND P.PCO_PERIODO = GASTO_COMUN.PCO_PERIODO
      AND GASTO_COMUN.ID_EDIFICIO = P.ID_EDIFICIO)
WHERE (GAS_GASTO_TOTAL - PGC_MONTO_CANCELADO > 0
   OR PGC_MONTO_CANCELADO IS NULL)
AND SUBSTR(GASTO_COMUN.PCO_PERIODO, 1, 4) = 2019 -- EXTRACT (YEAR FROM (TRUNC((SYSDATE -1), 'MONTH')))
AND SUBSTR(GASTO_COMUN.PCO_PERIODO, 5, 2) < 08 -- EXTRACT (MONTH FROM (TRUNC((SYSDATE -1), 'MONTH')))
ORDER BY
   3 ASC,
   1 ASC,
   5 DESC;

-----------------------------------------------------
-- 6
SELECT
   EDI_NOMBRE_EDIFICIO AS "EDIFICIO",
   NRO_DEPARTAMENTO AS "DEPARTAMENTO",
   SUBSTR(PCO_PERIODO, 5, 2) || '/' || SUBSTR(PCO_PERIODO, 1, 4) AS "PERIODO COBRO",
   GAS_FECHA_PAGO AS "FECHA DE PAGO",
   PGC_FECHA_CANCELACION AS "FECHA EN QUE CANCELÓ",
   TO_CHAR(GAS_GASTO_TOTAL, '$999G999G999') AS "TOTAL GASTO COMÚN",
   TO_CHAR(PGC_MONTO_CANCELADO, '$999G999G999') AS "MONTO CANCELADO",
   FPA_DESCRIPCION AS "FORMA DE PAGO"
FROM
   PAGO_GASTO_COMUN
   JOIN FORMA_PAGO USING (ID_FORMA_PAGO)
   NATURAL JOIN GASTO_COMUN
   JOIN EDIFICIO USING (ID_EDIFICIO)
WHERE
   EXTRACT(MONTH FROM GAS_FECHA_PAGO) = 08 -- EXTRACT(MONTH FROM (TRUNC((SYSDATE -1), 'MONTH')))
   AND EXTRACT(YEAR FROM GAS_FECHA_PAGO) = 2019 -- EXTRACT(YEAR FROM (TRUNC((SYSDATE -1), 'MONTH')))
ORDER BY
   1 ASC,
   2 ASC;

-----------------------------------------------------
-- 7
SELECT
   SUBSTR(PCO_PERIODO, 5, 2) || '/' || SUBSTR(PCO_PERIODO, 1, 4) AS "PERIODO COBRO GASTO COMÚN",
   EDI_NOMBRE_EDIFICIO AS "EDIFICIO",
   NRO_DEPARTAMENTO AS "NÚMERO DE DEPARTAMENTO"
FROM
   EDIFICIO
   JOIN (
      SELECT
         NRO_DEPARTAMENTO,
         PCO_PERIODO,
         ID_EDIFICIO
      FROM
         GASTO_COMUN MINUS
         SELECT
            NRO_DEPARTAMENTO,
            PCO_PERIODO,
            ID_EDIFICIO
         FROM
            PAGO_GASTO_COMUN)
         USING (ID_EDIFICIO)
      WHERE
         PCO_PERIODO = 201907 -- EXTRACT (YEAR FROM SYSDATE)||(EXTRACT(MONTH FROM SYSDATE)-1)
      ORDER BY
         EDI_NOMBRE_EDIFICIO,
         NRO_DEPARTAMENTO ASC;

-----------------------------------------------------
-- 8
SELECT
   EDI_NOMBRE_EDIFICIO AS "NOMBRE EDIFICIO",
   NOMBRE_COMUNA AS "COMUNA",
   GAS_FECHA_DESDE || '-' || GAS_FECHA_HASTA AS "PERIODO COBRO",
   COUNT(*) AS "TOTAL DEPARTAMENTOS",
   TO_CHAR(NVL (SUM(GAS_FONDO_RESERVA), 0),
      '$999G999G999') AS "FONDO RESERVA",
   TO_CHAR(NVL (SUM(GAS_AGUA_INDIVIDUAL), 0),
      '$999G999G999') AS "AGUA INDIVIDUAL",
   TO_CHAR(NVL (SUM(GAS_COMBUSTIBLE_INDIVIDUAL), 0),
      '$999G999G999') AS "COMBUSTIBLE INDIVBIDUAL",
   TO_CHAR(NVL (SUM(GAS_LAVANDERIA), 0),
      '$999G999G999') AS "LAVANDERÍA",
   TO_CHAR(NVL (SUM(GAS_EVENTOS), 0),
      '$999G999G999') AS "EVENTOS",
   TO_CHAR(NVL (SUM(GAS_GASTOS_ATRASADOS), 0),
      '$999G999G999') AS "GASTOS ATRASADOS",
   TO_CHAR(NVL (SUM(GAS_MULTAS), 0),
      '$999G999G999') AS "MULTAS",
   TO_CHAR(NVL (SUM(GAS_GASTO_TOTAL), 0),
      '$999G999G999') AS "TOTAL GASTOS COMUNES"
FROM
   GASTO_COMUN
   JOIN EDIFICIO USING (ID_EDIFICIO)
   JOIN COMUNA USING (ID_COMUNA)
WHERE
   SUBSTR(PCO_PERIODO, 0, 4) = 2018 -- EXTRACT (YEAR FROM (TRUNC((SYSDATE -1), 'MONTH')))-1
GROUP BY
   ID_EDIFICIO,
   EDIFICIO.EDI_NOMBRE_EDIFICIO,
   NOMBRE_COMUNA,
   GAS_FECHA_DESDE,
   GAS_FECHA_HASTA
ORDER BY
   3 ASC,
   1 ASC;

-----------------------------------------------------
-- 9
SELECT
   E.EDI_NOMBRE_EDIFICIO AS "EDIFICIO",
   G.NRO_DEPARTAMENTO AS "DEPARTAMENTO",
   TO_CHAR((SUM(GAS_GASTO_TOTAL) - SUM(PGC_MONTO_CANCELADO)),
      '$999G999G999') AS "DEUDA ACUMULADA"
FROM
   EDIFICIO E
   JOIN GASTO_COMUN G ON (E.ID_EDIFICIO = G.ID_EDIFICIO)
   LEFT JOIN PAGO_GASTO_COMUN P ON (G.ID_EDIFICIO = P.ID_EDIFICIO
      AND G.NRO_DEPARTAMENTO = P.NRO_DEPARTAMENTO
      AND G.PCO_PERIODO = P.PCO_PERIODO)
WHERE
   SUBSTR(G.PCO_PERIODO, 1, 4) = 2019 -- TRUNC(TRUNC((SYSDATE -1), 'MONTH')-1, 'MONTH')
   AND SUBSTR(G.PCO_PERIODO, 5, 2) < 07 -- TRUNC(TRUNC((SYSDATE -1), 'MONTH')-1, 'MONTH')
GROUP BY
   G.NRO_DEPARTAMENTO,
   E.EDI_NOMBRE_EDIFICIO
HAVING (SUM(GAS_GASTO_TOTAL) - SUM(PGC_MONTO_CANCELADO)) > (
   SELECT
      AVG(SUM(GAS_GASTO_TOTAL) - SUM(PGC_MONTO_CANCELADO))
   FROM
      GASTO_COMUN G
   LEFT JOIN PAGO_GASTO_COMUN P ON (G.ID_EDIFICIO = P.ID_EDIFICIO
      AND G.NRO_DEPARTAMENTO = P.NRO_DEPARTAMENTO
      AND G.PCO_PERIODO = P.PCO_PERIODO)
WHERE
   SUBSTR(G.PCO_PERIODO, 1, 4) = 2019 -- TRUNC(TRUNC((SYSDATE -1), 'MONTH')-1, 'MONTH')
   AND SUBSTR(G.PCO_PERIODO, 5, 2) < 07 -- TRUNC(TRUNC((SYSDATE -1), 'MONTH')-1, 'MONTH')
GROUP BY
   G.NRO_DEPARTAMENTO)
ORDER BY
   1 ASC,
   2 ASC;

-----------------------------------------------------
-- 10
CREATE TABLE PIVOTE
AS (
   SELECT
      G.ID_EDIFICIO,
      G.NRO_DEPARTAMENTO,
      G.PCO_PERIODO,
      CASE WHEN PGC_MONTO_CANCELADO IS NULL THEN
         3
         WHEN PGC_MONTO_CANCELADO < GAS_GASTO_TOTAL THEN
         2
         WHEN PGC_MONTO_CANCELADO = GAS_GASTO_TOTAL THEN
         1
      END AS ID_PIVOTE
   FROM
      GASTO_COMUN_PRUEBAESTPAGO G
   LEFT JOIN PAGO_GASTO_COMUN_PRUEBAESTPAGO P ON (G.PCO_PERIODO = P.PCO_PERIODO
      AND G.NRO_DEPARTAMENTO = P.NRO_DEPARTAMENTO
      AND G.ID_EDIFICIO = P.ID_EDIFICIO));

UPDATE
   GASTO_COMUN_PRUEBAESTPAGO A
SET
   ID_ESTADO_PAGO = (
      SELECT
         ID_PIVOTE
      FROM
         PIVOTE B
      WHERE
         A.ID_EDIFICIO = B.ID_EDIFICIO
         AND A.NRO_DEPARTAMENTO = B.NRO_DEPARTAMENTO
         AND A.PCO_PERIODO = B.PCO_PERIODO);
select * from GASTO_COMUN_PRUEBAESTPAGO;
DROP TABLE PIVOTE;

-----------------------------------------------------
-- 11
-- 11.1
SELECT
   PCO_PERIODO,
   ID_EDIFICIO,
   NRO_DEPARTAMENTO,
   PGC_MONTO_CANCELADO,
   ID_FORMA_PAGO
FROM
   PAGO_GASTO_COMUN_MENSUAL
INTERSECT
SELECT
   PCO_PERIODO,
   ID_EDIFICIO,
   NRO_DEPARTAMENTO,
   PGC_MONTO_CANCELADO,
   ID_FORMA_PAGO
FROM
   PAGO_GASTO_COMUN;

--11.2
SELECT
   PCO_PERIODO,
   ID_EDIFICIO,
   NRO_DEPARTAMENTO,
   PGC_MONTO_CANCELADO,
   ID_FORMA_PAGO
FROM
   PAGO_GASTO_COMUN_MENSUAL MINUS
   SELECT
      PCO_PERIODO,
      ID_EDIFICIO,
      NRO_DEPARTAMENTO,
      PGC_MONTO_CANCELADO,
      ID_FORMA_PAGO
   FROM
      PAGO_GASTO_COMUN;

-- 11.3
